2022-05-01 23:27:32,034 INFO    MainThread:193051 [internal.py:wandb_internal():90] W&B internal server running at pid: 193051, started at: 2022-05-01 23:27:32.033428
2022-05-01 23:27:32,036 INFO    WriterThread:193051 [datastore.py:open_for_write():75] open: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/run-1uydn1rj.wandb
2022-05-01 23:27:32,038 DEBUG   SenderThread:193051 [sender.py:send():232] send: header
2022-05-01 23:27:32,038 DEBUG   SenderThread:193051 [sender.py:send():232] send: run
2022-05-01 23:27:32,432 DEBUG   HandlerThread:193051 [handler.py:handle_request():141] handle_request: check_version
2022-05-01 23:27:32,436 INFO    SenderThread:193051 [dir_watcher.py:__init__():166] watching files in: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files
2022-05-01 23:27:32,437 INFO    SenderThread:193051 [sender.py:_start_run_threads():811] run started: 1uydn1rj with start time 1651415251
2022-05-01 23:27:32,437 DEBUG   SenderThread:193051 [sender.py:send():232] send: summary
2022-05-01 23:27:32,437 INFO    SenderThread:193051 [sender.py:_save_file():946] saving file wandb-summary.json with policy end
2022-05-01 23:27:32,437 DEBUG   SenderThread:193051 [sender.py:send_request():246] send_request: check_version
2022-05-01 23:27:32,495 DEBUG   HandlerThread:193051 [handler.py:handle_request():141] handle_request: run_start
2022-05-01 23:27:32,498 DEBUG   HandlerThread:193051 [meta.py:__init__():35] meta init
2022-05-01 23:27:32,498 DEBUG   HandlerThread:193051 [meta.py:__init__():49] meta init done
2022-05-01 23:27:32,498 DEBUG   HandlerThread:193051 [meta.py:probe():209] probe
2022-05-01 23:27:32,505 DEBUG   HandlerThread:193051 [meta.py:_setup_git():199] setup git
2022-05-01 23:27:32,522 DEBUG   HandlerThread:193051 [meta.py:_setup_git():206] setup git done
2022-05-01 23:27:32,522 DEBUG   HandlerThread:193051 [meta.py:_save_pip():53] save pip
2022-05-01 23:27:32,523 DEBUG   HandlerThread:193051 [meta.py:_save_pip():67] save pip done
2022-05-01 23:27:32,523 DEBUG   HandlerThread:193051 [meta.py:_save_conda():74] save conda
2022-05-01 23:27:33,438 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_created():213] file/dir created: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/conda-environment.yaml
2022-05-01 23:27:33,438 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_created():213] file/dir created: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/wandb-summary.json
2022-05-01 23:27:33,438 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_created():213] file/dir created: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/requirements.txt
2022-05-01 23:27:33,764 DEBUG   HandlerThread:193051 [meta.py:_save_conda():84] save conda done
2022-05-01 23:27:33,764 DEBUG   HandlerThread:193051 [meta.py:probe():247] probe done
2022-05-01 23:27:33,795 DEBUG   SenderThread:193051 [sender.py:send():232] send: files
2022-05-01 23:27:33,795 INFO    SenderThread:193051 [sender.py:_save_file():946] saving file wandb-metadata.json with policy now
2022-05-01 23:27:33,800 DEBUG   HandlerThread:193051 [handler.py:handle_request():141] handle_request: stop_status
2022-05-01 23:27:33,800 DEBUG   SenderThread:193051 [sender.py:send_request():246] send_request: stop_status
2022-05-01 23:27:34,060 DEBUG   SenderThread:193051 [sender.py:send():232] send: telemetry
2022-05-01 23:27:34,060 DEBUG   SenderThread:193051 [sender.py:send():232] send: telemetry
2022-05-01 23:27:34,061 DEBUG   SenderThread:193051 [sender.py:send():232] send: run
2022-05-01 23:27:34,438 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/config.yaml
2022-05-01 23:27:34,439 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_created():213] file/dir created: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/wandb-metadata.json
2022-05-01 23:27:34,439 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_created():213] file/dir created: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:27:34,448 INFO    SenderThread:193051 [sender.py:send_run():707] updated run: 1uydn1rj
2022-05-01 23:27:34,520 INFO    Thread-11 :193051 [upload_job.py:push():137] Uploaded file /tmp/tmpf_dbzldywandb/1o6l5n90-wandb-metadata.json
2022-05-01 23:27:36,438 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:27:40,439 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:27:44,441 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:27:48,442 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:27:49,083 DEBUG   HandlerThread:193051 [handler.py:handle_request():141] handle_request: stop_status
2022-05-01 23:27:49,084 DEBUG   SenderThread:193051 [sender.py:send_request():246] send_request: stop_status
2022-05-01 23:27:56,445 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:28:00,823 DEBUG   SenderThread:193051 [sender.py:send():232] send: stats
2022-05-01 23:28:04,366 DEBUG   HandlerThread:193051 [handler.py:handle_request():141] handle_request: stop_status
2022-05-01 23:28:10,453 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:28:12,454 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:28:14,454 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:28:16,455 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:28:18,456 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:28:20,457 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:28:22,458 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
2022-05-01 23:28:24,366 DEBUG   HandlerThread:193051 [handler.py:handle_request():141] handle_request: stop_status
2022-05-01 23:28:36,170 ERROR   SenderThread:193051 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/brain5/anaconda3/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/home/brain5/anaconda3/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/brain5/anaconda3/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/brain5/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/brain5/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/brain5/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2022-05-01 23:28:40,464 INFO    Thread-7  :193051 [dir_watcher.py:_on_file_modified():226] file/dir modified: /home/brain5/catkin_ws/src/social_navigation/scripts/wandb/run-20220501_232731-1uydn1rj/files/output.log
