
{'exp_name': 'pedsim', 'exp_epi_len': 1000, 'pi_hidden_layers': [128, 128], 'pi_options': ['default', 'leaky-relu', 'default'], 'replay_size': 10000, 'gamma': 0.99, 'polyak': 0.995, 'alpha': 0.002, 'learning_rate': 0.0001, 'epochs': 1000, 'steps_per_epoch': 4000, 'batch_size': 512, 'n_log_epi': 10, 'start_steps': 1000, 'update_after': 4000, 'update_every': 1000, 'save_interval': 10, 'plot_rendering': True, 'seed': 1}
goal reached!
goal reached!
lidar collision
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
goal reached!
lidar collision
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 127, in communicate_stop_status
Exception in thread NetStatThr:
Traceback (most recent call last):
    resp = self._communicate_stop_status(status)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 395, in _communicate_stop_status
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    resp = self._communicate(req, local=True)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    status_response = self._interface.communicate_network_status()
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 138, in communicate_network_status
    return self._communicate_async(rec, local=local).get(timeout=timeout)
    resp = self._communicate_network_status(status)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 405, in _communicate_network_status
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    resp = self._communicate(req, local=True)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception: The wandb backend process has shutdown
Traceback (most recent call last):
  File "sac_discrete_eval.py", line 284, in <module>
    wandb.log(log_infos)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1548, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1339, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1228, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 553, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 62, in _publish_partial_history
    self._publish(rec)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Traceback (most recent call last):
  File "sac_discrete_eval.py", line 284, in <module>
    wandb.log(log_infos)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1548, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1339, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1228, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 553, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 62, in _publish_partial_history
    self._publish(rec)
  File "/home/jay/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown